run:
  tests: false
  skip-dirs:
    - mocks
    - third_party$
    - builtin$
    - examples$

linters:
  enable:
    - bodyclose
    - containedctx
    - contextcheck
    - dupl
    - exhaustive
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - misspell
    - mnd
    - nestif
    - noctx
    - revive
    - rowserrcheck
    - sqlclosecheck
    - unconvert
    - staticcheck
    - errcheck
    - govet
    - ineffassign
    - unused
    - gofmt
    - goimports

linters-settings:
  errcheck:
    check-blank: true
  gocyclo:
    min-complexity: 30
  mnd:
    checks:
      - argument
      - case
      - condition
      - return
